#!/bin/sh
#
# start/stop mvtargetdaemon daemon.

### BEGIN INIT INFO
# Provides:          mvtargetdaemon
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       mv-target-daemon waits for MV-REQ-TARGET message via
#                    UDP from DevRocket, and sends back target informations
#                    such as ARCH, Linux Kernel Version, IP
### END INIT INFO

# Source function library.
. /etc/init.d/functions

DAEMON=/usr/sbin/mvtargetdaemon
NAME=mvtargetdaemon
PIDFILE=/var/run/$NAME.pid

test -f $DAEMON || exit 0

OPTIONS=""

start ()
{
    echo -n "Starting MontaVista target info daemon..."
    if pidof $DAEMON >/dev/null; then
        echo "already running."
        exit 0
    fi
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON
    if [ $? -eq 0 ]; then
        echo "done."
    else
        echo "failed."
    fi
}

stop ()
{
    echo "Stopping MontaVista target info daemon..."
    if ! pidof $DAEMON >/dev/null; then
        echo "not running."
        return 0
    fi
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON
    if [ $? -eq 0 ]; then
        rm -f $PIDFILE
        echo "done."
    else
        echo "failed."
    fi
}

case "$1" in
    start)
        start $OPTIONS
        ;;
    stop)
        stop
        ;;
    force-reload)
        stop
        start $OPTIONS
        ;;
    restart)
        stop
        start $OPTIONS
        ;;
    status)
        status $DAEMON
        ;;
    *)
        echo "Usage: /etc/init.d/mv-target-daemond {start|stop|force-reload|restart|status}"
        exit 1
        ;;
esac

exit $?
