#!/bin/bash

. /etc/init.d/functions
# Some functions are defined in /etc/init.d/functions.lsbinitscripts 
# but not in /etc/init.d/functions.
. /etc/init.d/functions.lsbinitscripts

LSB=LSB-1.1 killproc $*
exit $?
