#!/bin/bash

. /etc/init.d/functions
# Some functions are defined in /etc/init.d/functions.lsbinitscripts 
# but not in /etc/init.d/functions.
. /etc/init.d/functions.lsbinitscripts

ACTION=$1
shift

case "$ACTION" in
  success)
  	echo -n $*
	success "$*"
	echo
	;;
  failure)
  	echo -n $*
	failure "$*"
	echo
	;;
  echo_status)
	if [ -n "$2" ]; then
		echo -n "$1"
	else
		echo "$1"
	fi
	;;
  warning)
  	echo -n $*
	warning "$*"
	echo
	;;
  *)
  	;;
esac
exit 0
