#!/bin/sh 
### BEGIN INIT INFO
# Provides:             psplash
# Required-Start:
# Required-Stop:
# Default-Start:        S
# Default-Stop:
### END INIT INFO

[ -r /etc/default/rcS ] && . /etc/default/rcS

# Assume /dev/console mount on devpts is a container
# Set CONTAINER_OK in /etc/default/rcS to use in container
# IN_CONTAINER_ENV is set in /etc/default/rcS by lxc-mvlinux for container rootfs
([ -n "$IN_CONTAINER_ENV" ] || \
 [ -z "$CONTAINER_OK" -a "$(mount | grep 'devpts.*/dev/console')" ]) && exit 0

read CMDLINE < /proc/cmdline
for x in $CMDLINE; do
        case $x in
        psplash=false)
		echo "Boot splashscreen disabled" 
		exit 0;
                ;;
        esac
done

export TMPDIR=/mnt/.psplash
mount tmpfs -t tmpfs $TMPDIR -o,size=40k

rotation=0
if [ -e /etc/rotation ]; then
	read rotation < /etc/rotation
fi

/usr/bin/psplash --angle $rotation &

